# Site settings
title: Yuan Tang
SEOTitle: Yuan's Blog
header-img: img/home-bg.jpg
email: terrytangyuan@gmail.com
description: ""
keyword: ""
url: "http://snowdj.github.io"              # your host, for absolute URL
baseurl: "/terry"                             # for example, '/blog' if your blog hosted on 'host/blog'
gems: [jekyll-paginate]

# SNS settings
RSS: false
weibo_username:     唐源Terry
#zhihu_username:     terrytangyuan
github_username:    terrytangyuan
twitter_username:  terrytangyuan
#facebook_username:  terrytangyuan
linkedin_visitor_id: yuan-terry-tang-117ba962


# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: terrytangyuan

# Duoshuo settings
duoshuo_username: terrytangyuan
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-74985813-1'            # Format: UA-xxxxxx-xx
ga_domain: terrytangyuan.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Live deeply, live fully, and live with love."
sidebar-avatar: /img/final_prof_pic_2.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Affliations
affliations: [
    {
        title: "Uptake",
        href: "http://uptake.com" 
    },{
        title: "RStudio",
        href: "http://rstudio.com/"
    },{
        title: "DMLC",
        href: "http://dmlc.ml/"
    },{
        title: "TensorFlow",
        href: "https://github.com/tensorflow"
    },{
        title: "DataNovo",
        href: "http://datanovo.com"
    },{
        title: "Gastrograph",
        href: "http://gastrograph.com"
    },{
        title: "Penn State University",
        href: "http://psu.edu/"
    }
]
